version: '3.8'

services:
  web:
    image: my-flask-app-image
    build: .
    container_name: flask-app
    ports:
      - "5000:5000"
    volumes:
      - ./templates:/app/templates
    restart: always
